name: depechemode
favicon: null
layout_spectrum: 0.29171
typography_spectrum: 0.4038562634959817
title: t-shirt fundraising   made in germany
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfe'
    - '#81a4ca'
    - '#740001'
    - '#1f232c'
    - '#8e6c46'
  brandStrength: 1
  lightness: 0.9014149983413517
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
